### ISSUE TITLE
More algos required.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/CAO_Shortcuts#1]
Any algorithm in python related to COA/CAO concepts can be added.
Needed:
1. Booths algorithm (normal and advanced)
2. And so on...

**Comment by tamal78** [comment]
i can give c++ and java code for booth's multiplication algorithm

**Comment by nkhandelwal07** [comment]
Can you assign this to me please? i'd like to add a logic gate.

**Comment by Abhiramborige** [comment]
Yup sure, I will assign you.

**Comment by tamal78** [comment]
i have added my pr please review and merge and add tag hactoberfest and hactoberfest-accepted

**Comment by Abhiramborige** [comment]
I will close it now, I got my mistake.
